# Generated by Django 5.2.7 on 2025-10-08 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feria',
            fields=[
                ('id_feria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_feria', models.CharField(max_length=100)),
                ('ubicacion_feria', models.CharField(blank=True, max_length=200, null=True)),
                ('aglomeracion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('numero_puesto', models.CharField(blank=True, max_length=20, null=True)),
                ('id_feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appferiadigital.feria')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='appferiadigital.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appferiadigital.categoria')),
                ('id_puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appferiadigital.puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appferiadigital.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reserva', models.IntegerField()),
                ('unidad_de_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appferiadigital.producto')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appferiadigital.reserva')),
            ],
            options={
                'unique_together': {('id_reserva', 'id_producto')},
            },
        ),
    ]
