# Generated by Django 5.2.8 on 2025-12-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appferiadigital', '0002_reserva_cantidad_reserva_id_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feria',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feria',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='feria',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
