# Generated by Django 5.2.8 on 2025-12-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appferiadigital', '0003_feria_ciudad_feria_latitud_feria_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feria',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='feria',
            name='longitud',
        ),
    ]
